name: ci-build

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x64
          - os: ubuntu-24.04-arm
            arch: arm64
          - os: windows-2022
            arch: x64
          - os: windows-11-arm
            arch: arm64
          - os: macos-13
            arch: x64
          - os: macos-14
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: bindiff
      - uses: actions/checkout@v4
        with:
          repository: google/binexport
          path: binexport

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Enable Developer Command Prompt
        if: startsWith(matrix.os, 'windows-')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          cmake -S bindiff -B build -G Ninja \
            -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
            -DBINDIFF_BINEXPORT_DIR="${GITHUB_WORKSPACE}/binexport"

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config "${BUILD_TYPE}"

      - name: Test
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: ctest --build-config "${BUILD_TYPE}" --output-on-failure -R '^[A-Z]'
